package com.tj720.dao;


import java.util.List;

import com.tj720.controller.base.dao.BaseDao;
import com.tj720.model.common.system.menu.MenuZtreeNode;
import com.tj720.model.common.system.role.MipRoleMenu;
import com.tj720.model.common.system.role.MipRoleMenuExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MipRoleMenuMapper extends BaseDao<MipRoleMenu> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
//    int countByExample(MipRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
//    int deleteByExample(MipRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
    int insert(MipRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
    int insertSelective(MipRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
//    List<MipRoleMenu> selectByExample(MipRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
    MipRoleMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
//    int updateByExampleSelective(@Param("record") MipRoleMenu record, @Param("example") MipRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
//    int updateByExample(@Param("record") MipRoleMenu record, @Param("example") MipRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
    int updateByPrimaryKeySelective(MipRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_role_menu
     *
     * @mbggenerated Thu Jun 28 15:17:25 CST 2018
     */
    int updateByPrimaryKey(MipRoleMenu record);
    
    List<MenuZtreeNode> selectMenuByRoleId(@Param("roleid") String roleid);
    
    int insertByBatch(@Param("list") List<MipRoleMenu> list);
}