package com.tj720.dao;


import com.tj720.controller.base.dao.BaseDao;
import com.tj720.model.common.system.user.MipUserRole;
import com.tj720.model.common.system.user.MipUserRoleExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("mipUserRoleMapper")
public interface MipUserRoleMapper extends BaseDao<MipUserRole> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
//    int countByExample(MipUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
//    int deleteByExample(MipUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
//    List<MipUserRole> selectByExample(MipUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
//    int updateByExampleSelective(@Param("record") MipUserRole record, @Param("example") MipUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
//    int updateByExample(@Param("record") MipUserRole record, @Param("example") MipUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_user_role
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipUserRole record);

	void batchInsert(List<MipUserRole> userRoleList);

	List<MipUserRole> getByUserId(String id);

	void deleteByUserId(String userId);
}