package com.tj720.dao;

import com.tj720.model.common.system.process.ProcessInstanceInfo;
import com.tj720.model.common.system.process.ProcessInstanceInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface ProcessInstanceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
//    int countByExample(ProcessInstanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
//    int deleteByExample(ProcessInstanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    int deleteByPrimaryKey(String xid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    int insert(ProcessInstanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    int insertSelective(ProcessInstanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
//    List<ProcessInstanceInfo> selectByExample(ProcessInstanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    ProcessInstanceInfo selectByPrimaryKey(String xid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
//    int updateByExampleSelective(@Param("record") ProcessInstanceInfo record, @Param("example") ProcessInstanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
//    int updateByExample(@Param("record") ProcessInstanceInfo record, @Param("example") ProcessInstanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    int updateByPrimaryKeySelective(ProcessInstanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_instance
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    int updateByPrimaryKey(ProcessInstanceInfo record);
}