package com.tj720.dao;

import com.tj720.model.common.system.menu.MenuTreeDto;
import com.tj720.model.common.system.menu.SysFunction;
import com.tj720.model.common.system.menu.SysFunctionExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface SysFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
//    int countByExample(SysFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
//    int deleteByExample(SysFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    int insert(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    int insertSelective(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
//    List<SysFunction> selectByExample(SysFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    SysFunction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
//    int updateByExampleSelective(@Param("record") SysFunction record, @Param("example") SysFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
//    int updateByExample(@Param("record") SysFunction record, @Param("example") SysFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    int updateByPrimaryKeySelective(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    int updateByPrimaryKey(SysFunction record);

    /**
     * 条件查询功能列表
     * @param type
     * @return
     */
    List<MenuTreeDto> selectByCondition(@Param("type") String type,@Param("functionName") String functionName);

    /**
     * 根据id查询功能
     * @param functionId 功能id
     * @return
     */
    SysFunction selectFunctionById(@Param("functionId") String functionId);

    /**
     * 根据父id和类型查询子功能
     * @param parentId 父ID
     * @param type 类型
     * @return
     */
    List<SysFunction> selectByParentId(@Param("parentId") String parentId,@Param("type") String type);

    List<SysFunction> selectByFunctionName(String functionName);
}