package com.tj720.dao;

import com.tj720.model.common.system.role.SysRole;
import com.tj720.model.common.system.role.SysRoleExample;
import com.tj720.utils.Page;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.HashMap;
import java.util.List;
@Repository
public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
//    int countByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
//    int deleteByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
//    List<SysRole> selectByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
    SysRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
//    int updateByExampleSelective(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
//    int updateByExample(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Oct 09 17:21:16 CST 2018
     */
    int updateByPrimaryKey(SysRole record);

    /**
     * 查询角色列表
     * @param roleCode 角色编码
     * @param roleName 角色名称
     * @param start 开始页数
     * @param end 页数大小
     * @return
     */
    List<SysRole> selectByCondition(@Param("roleCode") String roleCode,@Param("roleName") String roleName,
                                    @Param("start") int start,@Param("end") int end);

    /**
     * 查询角色列表总数
     * @param roleCode 角色编码
     * @param roleName 角色名称
     * @return
     */
    Integer countByCondition(@Param("roleCode") String roleCode,@Param("roleName") String roleName);

    /**
     * 查询角色列表
     * @return
     */
    List<SysRole> getRoleList();

    List<SysRole> getRoleListByRoleCode(String roleCode);
}