package com.tj720.model.common;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AttachmentExample implements Serializable{

    private static final long serialVersionUID = -4790659145646331596L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public AttachmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAttIdIsNull() {
            addCriterion("att_id is null");
            return (Criteria) this;
        }

        public Criteria andAttIdIsNotNull() {
            addCriterion("att_id is not null");
            return (Criteria) this;
        }

        public Criteria andAttIdEqualTo(String value) {
            addCriterion("att_id =", value, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdNotEqualTo(String value) {
            addCriterion("att_id <>", value, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdGreaterThan(String value) {
            addCriterion("att_id >", value, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdGreaterThanOrEqualTo(String value) {
            addCriterion("att_id >=", value, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdLessThan(String value) {
            addCriterion("att_id <", value, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdLessThanOrEqualTo(String value) {
            addCriterion("att_id <=", value, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdLike(String value) {
            addCriterion("att_id like", value, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdNotLike(String value) {
            addCriterion("att_id not like", value, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdIn(List<String> values) {
            addCriterion("att_id in", values, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdNotIn(List<String> values) {
            addCriterion("att_id not in", values, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdBetween(String value1, String value2) {
            addCriterion("att_id between", value1, value2, "attId");
            return (Criteria) this;
        }

        public Criteria andAttIdNotBetween(String value1, String value2) {
            addCriterion("att_id not between", value1, value2, "attId");
            return (Criteria) this;
        }

        public Criteria andAttNameIsNull() {
            addCriterion("att_name is null");
            return (Criteria) this;
        }

        public Criteria andAttNameIsNotNull() {
            addCriterion("att_name is not null");
            return (Criteria) this;
        }

        public Criteria andAttNameEqualTo(String value) {
            addCriterion("att_name =", value, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameNotEqualTo(String value) {
            addCriterion("att_name <>", value, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameGreaterThan(String value) {
            addCriterion("att_name >", value, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameGreaterThanOrEqualTo(String value) {
            addCriterion("att_name >=", value, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameLessThan(String value) {
            addCriterion("att_name <", value, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameLessThanOrEqualTo(String value) {
            addCriterion("att_name <=", value, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameLike(String value) {
            addCriterion("att_name like", value, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameNotLike(String value) {
            addCriterion("att_name not like", value, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameIn(List<String> values) {
            addCriterion("att_name in", values, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameNotIn(List<String> values) {
            addCriterion("att_name not in", values, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameBetween(String value1, String value2) {
            addCriterion("att_name between", value1, value2, "attName");
            return (Criteria) this;
        }

        public Criteria andAttNameNotBetween(String value1, String value2) {
            addCriterion("att_name not between", value1, value2, "attName");
            return (Criteria) this;
        }

        public Criteria andAttSizeIsNull() {
            addCriterion("att_size is null");
            return (Criteria) this;
        }

        public Criteria andAttSizeIsNotNull() {
            addCriterion("att_size is not null");
            return (Criteria) this;
        }

        public Criteria andAttSizeEqualTo(Long value) {
            addCriterion("att_size =", value, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeNotEqualTo(Long value) {
            addCriterion("att_size <>", value, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeGreaterThan(Long value) {
            addCriterion("att_size >", value, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("att_size >=", value, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeLessThan(Long value) {
            addCriterion("att_size <", value, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeLessThanOrEqualTo(Long value) {
            addCriterion("att_size <=", value, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeIn(List<Long> values) {
            addCriterion("att_size in", values, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeNotIn(List<Long> values) {
            addCriterion("att_size not in", values, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeBetween(Long value1, Long value2) {
            addCriterion("att_size between", value1, value2, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttSizeNotBetween(Long value1, Long value2) {
            addCriterion("att_size not between", value1, value2, "attSize");
            return (Criteria) this;
        }

        public Criteria andAttPathIsNull() {
            addCriterion("att_path is null");
            return (Criteria) this;
        }

        public Criteria andAttPathIsNotNull() {
            addCriterion("att_path is not null");
            return (Criteria) this;
        }

        public Criteria andAttPathEqualTo(String value) {
            addCriterion("att_path =", value, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathNotEqualTo(String value) {
            addCriterion("att_path <>", value, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathGreaterThan(String value) {
            addCriterion("att_path >", value, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathGreaterThanOrEqualTo(String value) {
            addCriterion("att_path >=", value, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathLessThan(String value) {
            addCriterion("att_path <", value, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathLessThanOrEqualTo(String value) {
            addCriterion("att_path <=", value, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathLike(String value) {
            addCriterion("att_path like", value, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathNotLike(String value) {
            addCriterion("att_path not like", value, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathIn(List<String> values) {
            addCriterion("att_path in", values, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathNotIn(List<String> values) {
            addCriterion("att_path not in", values, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathBetween(String value1, String value2) {
            addCriterion("att_path between", value1, value2, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttPathNotBetween(String value1, String value2) {
            addCriterion("att_path not between", value1, value2, "attPath");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkIsNull() {
            addCriterion("att_isJunk is null");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkIsNotNull() {
            addCriterion("att_isJunk is not null");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkEqualTo(String value) {
            addCriterion("att_isJunk =", value, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkNotEqualTo(String value) {
            addCriterion("att_isJunk <>", value, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkGreaterThan(String value) {
            addCriterion("att_isJunk >", value, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkGreaterThanOrEqualTo(String value) {
            addCriterion("att_isJunk >=", value, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkLessThan(String value) {
            addCriterion("att_isJunk <", value, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkLessThanOrEqualTo(String value) {
            addCriterion("att_isJunk <=", value, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkLike(String value) {
            addCriterion("att_isJunk like", value, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkNotLike(String value) {
            addCriterion("att_isJunk not like", value, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkIn(List<String> values) {
            addCriterion("att_isJunk in", values, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkNotIn(List<String> values) {
            addCriterion("att_isJunk not in", values, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkBetween(String value1, String value2) {
            addCriterion("att_isJunk between", value1, value2, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttIsjunkNotBetween(String value1, String value2) {
            addCriterion("att_isJunk not between", value1, value2, "attIsjunk");
            return (Criteria) this;
        }

        public Criteria andAttDateIsNull() {
            addCriterion("att_date is null");
            return (Criteria) this;
        }

        public Criteria andAttDateIsNotNull() {
            addCriterion("att_date is not null");
            return (Criteria) this;
        }

        public Criteria andAttDateEqualTo(Date value) {
            addCriterion("att_date =", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotEqualTo(Date value) {
            addCriterion("att_date <>", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateGreaterThan(Date value) {
            addCriterion("att_date >", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateGreaterThanOrEqualTo(Date value) {
            addCriterion("att_date >=", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateLessThan(Date value) {
            addCriterion("att_date <", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateLessThanOrEqualTo(Date value) {
            addCriterion("att_date <=", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateIn(List<Date> values) {
            addCriterion("att_date in", values, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotIn(List<Date> values) {
            addCriterion("att_date not in", values, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateBetween(Date value1, Date value2) {
            addCriterion("att_date between", value1, value2, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotBetween(Date value1, Date value2) {
            addCriterion("att_date not between", value1, value2, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttTypeIsNull() {
            addCriterion("att_type is null");
            return (Criteria) this;
        }

        public Criteria andAttTypeIsNotNull() {
            addCriterion("att_type is not null");
            return (Criteria) this;
        }

        public Criteria andAttTypeEqualTo(String value) {
            addCriterion("att_type =", value, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeNotEqualTo(String value) {
            addCriterion("att_type <>", value, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeGreaterThan(String value) {
            addCriterion("att_type >", value, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeGreaterThanOrEqualTo(String value) {
            addCriterion("att_type >=", value, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeLessThan(String value) {
            addCriterion("att_type <", value, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeLessThanOrEqualTo(String value) {
            addCriterion("att_type <=", value, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeLike(String value) {
            addCriterion("att_type like", value, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeNotLike(String value) {
            addCriterion("att_type not like", value, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeIn(List<String> values) {
            addCriterion("att_type in", values, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeNotIn(List<String> values) {
            addCriterion("att_type not in", values, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeBetween(String value1, String value2) {
            addCriterion("att_type between", value1, value2, "attType");
            return (Criteria) this;
        }

        public Criteria andAttTypeNotBetween(String value1, String value2) {
            addCriterion("att_type not between", value1, value2, "attType");
            return (Criteria) this;
        }

        public Criteria andAttrUserIsNull() {
            addCriterion("attr_user is null");
            return (Criteria) this;
        }

        public Criteria andAttrUserIsNotNull() {
            addCriterion("attr_user is not null");
            return (Criteria) this;
        }

        public Criteria andAttrUserEqualTo(String value) {
            addCriterion("attr_user =", value, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserNotEqualTo(String value) {
            addCriterion("attr_user <>", value, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserGreaterThan(String value) {
            addCriterion("attr_user >", value, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserGreaterThanOrEqualTo(String value) {
            addCriterion("attr_user >=", value, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserLessThan(String value) {
            addCriterion("attr_user <", value, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserLessThanOrEqualTo(String value) {
            addCriterion("attr_user <=", value, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserLike(String value) {
            addCriterion("attr_user like", value, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserNotLike(String value) {
            addCriterion("attr_user not like", value, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserIn(List<String> values) {
            addCriterion("attr_user in", values, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserNotIn(List<String> values) {
            addCriterion("attr_user not in", values, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserBetween(String value1, String value2) {
            addCriterion("attr_user between", value1, value2, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttrUserNotBetween(String value1, String value2) {
            addCriterion("attr_user not between", value1, value2, "attrUser");
            return (Criteria) this;
        }

        public Criteria andAttFkIdIsNull() {
            addCriterion("att_fk_id is null");
            return (Criteria) this;
        }

        public Criteria andAttFkIdIsNotNull() {
            addCriterion("att_fk_id is not null");
            return (Criteria) this;
        }

        public Criteria andAttFkIdEqualTo(String value) {
            addCriterion("att_fk_id =", value, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdNotEqualTo(String value) {
            addCriterion("att_fk_id <>", value, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdGreaterThan(String value) {
            addCriterion("att_fk_id >", value, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdGreaterThanOrEqualTo(String value) {
            addCriterion("att_fk_id >=", value, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdLessThan(String value) {
            addCriterion("att_fk_id <", value, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdLessThanOrEqualTo(String value) {
            addCriterion("att_fk_id <=", value, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdLike(String value) {
            addCriterion("att_fk_id like", value, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdNotLike(String value) {
            addCriterion("att_fk_id not like", value, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdIn(List<String> values) {
            addCriterion("att_fk_id in", values, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdNotIn(List<String> values) {
            addCriterion("att_fk_id not in", values, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdBetween(String value1, String value2) {
            addCriterion("att_fk_id between", value1, value2, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFkIdNotBetween(String value1, String value2) {
            addCriterion("att_fk_id not between", value1, value2, "attFkId");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeIsNull() {
            addCriterion("att_file_type is null");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeIsNotNull() {
            addCriterion("att_file_type is not null");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeEqualTo(Integer value) {
            addCriterion("att_file_type =", value, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeNotEqualTo(Integer value) {
            addCriterion("att_file_type <>", value, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeGreaterThan(Integer value) {
            addCriterion("att_file_type >", value, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("att_file_type >=", value, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeLessThan(Integer value) {
            addCriterion("att_file_type <", value, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeLessThanOrEqualTo(Integer value) {
            addCriterion("att_file_type <=", value, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeIn(List<Integer> values) {
            addCriterion("att_file_type in", values, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeNotIn(List<Integer> values) {
            addCriterion("att_file_type not in", values, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeBetween(Integer value1, Integer value2) {
            addCriterion("att_file_type between", value1, value2, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttFileTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("att_file_type not between", value1, value2, "attFileType");
            return (Criteria) this;
        }

        public Criteria andAttSourceIsNull() {
            addCriterion("att_source is null");
            return (Criteria) this;
        }

        public Criteria andAttSourceIsNotNull() {
            addCriterion("att_source is not null");
            return (Criteria) this;
        }

        public Criteria andAttSourceEqualTo(String value) {
            addCriterion("att_source =", value, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceNotEqualTo(String value) {
            addCriterion("att_source <>", value, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceGreaterThan(String value) {
            addCriterion("att_source >", value, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceGreaterThanOrEqualTo(String value) {
            addCriterion("att_source >=", value, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceLessThan(String value) {
            addCriterion("att_source <", value, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceLessThanOrEqualTo(String value) {
            addCriterion("att_source <=", value, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceLike(String value) {
            addCriterion("att_source like", value, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceNotLike(String value) {
            addCriterion("att_source not like", value, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceIn(List<String> values) {
            addCriterion("att_source in", values, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceNotIn(List<String> values) {
            addCriterion("att_source not in", values, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceBetween(String value1, String value2) {
            addCriterion("att_source between", value1, value2, "attSource");
            return (Criteria) this;
        }

        public Criteria andAttSourceNotBetween(String value1, String value2) {
            addCriterion("att_source not between", value1, value2, "attSource");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_attachment
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 02 10:27:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_attachment
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}