package com.tj720.model.common;

public class SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.url
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.ip
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.start_date
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private Long startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.end_date
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private Long endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_data
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private String requestData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_id
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.isAjax
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private Integer isajax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.statusCode
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private String statuscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.errorMsg
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    private String errormsg;

    
    
    public SysLog() {
		super();
		// TODO Auto-generated constructor stub
	}

	public SysLog(Integer id, String url, String ip, Long startDate, Long endDate, String requestData,
			String userId, Integer isajax, String statuscode, String errormsg) {
		super();
		this.id = id;
		this.url = url;
		this.ip = ip;
		this.startDate = startDate;
		this.endDate = endDate;
		this.requestData = requestData;
		this.userId = userId;
		this.isajax = isajax;
		this.statuscode = statuscode;
		this.errormsg = errormsg;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.url
     *
     * @return the value of sys_log.url
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.url
     *
     * @param url the value for sys_log.url
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.ip
     *
     * @return the value of sys_log.ip
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.ip
     *
     * @param ip the value for sys_log.ip
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.start_date
     *
     * @return the value of sys_log.start_date
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public Long getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.start_date
     *
     * @param startDate the value for sys_log.start_date
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setStartDate(Long startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.end_date
     *
     * @return the value of sys_log.end_date
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public Long getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.end_date
     *
     * @param endDate the value for sys_log.end_date
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setEndDate(Long endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_data
     *
     * @return the value of sys_log.request_data
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public String getRequestData() {
        return requestData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_data
     *
     * @param requestData the value for sys_log.request_data
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setRequestData(String requestData) {
        this.requestData = requestData == null ? null : requestData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_id
     *
     * @return the value of sys_log.user_id
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_id
     *
     * @param userId the value for sys_log.user_id
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.isAjax
     *
     * @return the value of sys_log.isAjax
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public Integer getIsajax() {
        return isajax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.isAjax
     *
     * @param isajax the value for sys_log.isAjax
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setIsajax(Integer isajax) {
        this.isajax = isajax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.statusCode
     *
     * @return the value of sys_log.statusCode
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public String getStatuscode() {
        return statuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.statusCode
     *
     * @param statuscode the value for sys_log.statusCode
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode == null ? null : statuscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.errorMsg
     *
     * @return the value of sys_log.errorMsg
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public String getErrormsg() {
        return errormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.errorMsg
     *
     * @param errormsg the value for sys_log.errorMsg
     *
     * @mbggenerated Fri Jul 20 16:42:02 CST 2018
     */
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg == null ? null : errormsg.trim();
    }
}