package com.tj720.model.common.system.menu;

import java.util.Date;

public class MipMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.menuName
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.menuUrl
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String menuurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.roleIds
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String roleids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.parentId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.iconRemark
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String iconremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_menu.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;
    
    private String parentname;

    public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.id
     *
     * @return the value of mip_menu.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.id
     *
     * @param id the value for mip_menu.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.menuName
     *
     * @return the value of mip_menu.menuName
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.menuName
     *
     * @param menuname the value for mip_menu.menuName
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.menuUrl
     *
     * @return the value of mip_menu.menuUrl
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.menuUrl
     *
     * @param menuurl the value for mip_menu.menuUrl
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.roleIds
     *
     * @return the value of mip_menu.roleIds
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getRoleids() {
        return roleids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.roleIds
     *
     * @param roleids the value for mip_menu.roleIds
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setRoleids(String roleids) {
        this.roleids = roleids == null ? null : roleids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.parentId
     *
     * @return the value of mip_menu.parentId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.parentId
     *
     * @param parentid the value for mip_menu.parentId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.iconRemark
     *
     * @return the value of mip_menu.iconRemark
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getIconremark() {
        return iconremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.iconRemark
     *
     * @param iconremark the value for mip_menu.iconRemark
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setIconremark(String iconremark) {
        this.iconremark = iconremark == null ? null : iconremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.type
     *
     * @return the value of mip_menu.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.type
     *
     * @param type the value for mip_menu.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.createTime
     *
     * @return the value of mip_menu.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.createTime
     *
     * @param createtime the value for mip_menu.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.status
     *
     * @return the value of mip_menu.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.status
     *
     * @param status the value for mip_menu.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_menu.sequence
     *
     * @return the value of mip_menu.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_menu.sequence
     *
     * @param sequence the value for mip_menu.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}