package com.tj720.model.common.system.role;

import java.util.Date;

public class MipRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.parent_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.name
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.remark
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.status
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.isdelete
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private Byte isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.creator_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.updater_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.createTime
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.update_time
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.sequence
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_role.orgType
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    private String orgtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.id
     *
     * @return the value of mip_role.id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.id
     *
     * @param id the value for mip_role.id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.parent_id
     *
     * @return the value of mip_role.parent_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.parent_id
     *
     * @param parentId the value for mip_role.parent_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.name
     *
     * @return the value of mip_role.name
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.name
     *
     * @param name the value for mip_role.name
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.remark
     *
     * @return the value of mip_role.remark
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.remark
     *
     * @param remark the value for mip_role.remark
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.status
     *
     * @return the value of mip_role.status
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.status
     *
     * @param status the value for mip_role.status
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.isdelete
     *
     * @return the value of mip_role.isdelete
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.isdelete
     *
     * @param isdelete the value for mip_role.isdelete
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.creator_id
     *
     * @return the value of mip_role.creator_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.creator_id
     *
     * @param creatorId the value for mip_role.creator_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.updater_id
     *
     * @return the value of mip_role.updater_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.updater_id
     *
     * @param updaterId the value for mip_role.updater_id
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.createTime
     *
     * @return the value of mip_role.createTime
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.createTime
     *
     * @param createtime the value for mip_role.createTime
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.update_time
     *
     * @return the value of mip_role.update_time
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.update_time
     *
     * @param updateTime the value for mip_role.update_time
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.sequence
     *
     * @return the value of mip_role.sequence
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.sequence
     *
     * @param sequence the value for mip_role.sequence
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_role.orgType
     *
     * @return the value of mip_role.orgType
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public String getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_role.orgType
     *
     * @param orgtype the value for mip_role.orgType
     *
     * @mbggenerated Mon Jul 02 18:30:00 CST 2018
     */
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype == null ? null : orgtype.trim();
    }
}