package com.tj720.model.common.system.process;

public class ProcessConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.xid
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String xid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.process_def_id
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String processDefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.process_def_name
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String processDefName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.activity_id
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.activity_name
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.normal_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String normalParticipant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.group_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String groupParticipant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.complex_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String complexParticipant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.complex_type
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String complexType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.participant_rule
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String participantRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.sort
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.drill_down
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String drillDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.drill_up
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String drillUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.ext1
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.ext2
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_config.ext3
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    private String ext3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.xid
     *
     * @return the value of process_config.xid
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getXid() {
        return xid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.xid
     *
     * @param xid the value for process_config.xid
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setXid(String xid) {
        this.xid = xid == null ? null : xid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.process_def_id
     *
     * @return the value of process_config.process_def_id
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getProcessDefId() {
        return processDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.process_def_id
     *
     * @param processDefId the value for process_config.process_def_id
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setProcessDefId(String processDefId) {
        this.processDefId = processDefId == null ? null : processDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.process_def_name
     *
     * @return the value of process_config.process_def_name
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getProcessDefName() {
        return processDefName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.process_def_name
     *
     * @param processDefName the value for process_config.process_def_name
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setProcessDefName(String processDefName) {
        this.processDefName = processDefName == null ? null : processDefName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.activity_id
     *
     * @return the value of process_config.activity_id
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.activity_id
     *
     * @param activityId the value for process_config.activity_id
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.activity_name
     *
     * @return the value of process_config.activity_name
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.activity_name
     *
     * @param activityName the value for process_config.activity_name
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.normal_participant
     *
     * @return the value of process_config.normal_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getNormalParticipant() {
        return normalParticipant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.normal_participant
     *
     * @param normalParticipant the value for process_config.normal_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setNormalParticipant(String normalParticipant) {
        this.normalParticipant = normalParticipant == null ? null : normalParticipant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.group_participant
     *
     * @return the value of process_config.group_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getGroupParticipant() {
        return groupParticipant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.group_participant
     *
     * @param groupParticipant the value for process_config.group_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setGroupParticipant(String groupParticipant) {
        this.groupParticipant = groupParticipant == null ? null : groupParticipant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.complex_participant
     *
     * @return the value of process_config.complex_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getComplexParticipant() {
        return complexParticipant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.complex_participant
     *
     * @param complexParticipant the value for process_config.complex_participant
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setComplexParticipant(String complexParticipant) {
        this.complexParticipant = complexParticipant == null ? null : complexParticipant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.complex_type
     *
     * @return the value of process_config.complex_type
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getComplexType() {
        return complexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.complex_type
     *
     * @param complexType the value for process_config.complex_type
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setComplexType(String complexType) {
        this.complexType = complexType == null ? null : complexType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.participant_rule
     *
     * @return the value of process_config.participant_rule
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getParticipantRule() {
        return participantRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.participant_rule
     *
     * @param participantRule the value for process_config.participant_rule
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setParticipantRule(String participantRule) {
        this.participantRule = participantRule == null ? null : participantRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.sort
     *
     * @return the value of process_config.sort
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.sort
     *
     * @param sort the value for process_config.sort
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.drill_down
     *
     * @return the value of process_config.drill_down
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getDrillDown() {
        return drillDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.drill_down
     *
     * @param drillDown the value for process_config.drill_down
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setDrillDown(String drillDown) {
        this.drillDown = drillDown == null ? null : drillDown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.drill_up
     *
     * @return the value of process_config.drill_up
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getDrillUp() {
        return drillUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.drill_up
     *
     * @param drillUp the value for process_config.drill_up
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setDrillUp(String drillUp) {
        this.drillUp = drillUp == null ? null : drillUp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.ext1
     *
     * @return the value of process_config.ext1
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.ext1
     *
     * @param ext1 the value for process_config.ext1
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.ext2
     *
     * @return the value of process_config.ext2
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.ext2
     *
     * @param ext2 the value for process_config.ext2
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_config.ext3
     *
     * @return the value of process_config.ext3
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_config.ext3
     *
     * @param ext3 the value for process_config.ext3
     *
     * @mbggenerated Thu Sep 27 10:46:44 CST 2018
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }
}