package com.tj720.model.common.system.process;

import java.util.Date;

public class WorkitemDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.xid
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String xid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.process_instance_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String processInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.work_item_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String workItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.work_item_name
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String workItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.activity_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.activity_name
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.operator
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.operate_time
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.approval_comment
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String approvalComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.remark
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.status
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.ext1
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.ext2
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workitem_detail.ext3
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    private String ext3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.xid
     *
     * @return the value of workitem_detail.xid
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getXid() {
        return xid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.xid
     *
     * @param xid the value for workitem_detail.xid
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setXid(String xid) {
        this.xid = xid == null ? null : xid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.process_instance_id
     *
     * @return the value of workitem_detail.process_instance_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.process_instance_id
     *
     * @param processInstanceId the value for workitem_detail.process_instance_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId == null ? null : processInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.work_item_id
     *
     * @return the value of workitem_detail.work_item_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getWorkItemId() {
        return workItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.work_item_id
     *
     * @param workItemId the value for workitem_detail.work_item_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setWorkItemId(String workItemId) {
        this.workItemId = workItemId == null ? null : workItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.work_item_name
     *
     * @return the value of workitem_detail.work_item_name
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getWorkItemName() {
        return workItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.work_item_name
     *
     * @param workItemName the value for workitem_detail.work_item_name
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setWorkItemName(String workItemName) {
        this.workItemName = workItemName == null ? null : workItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.activity_id
     *
     * @return the value of workitem_detail.activity_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.activity_id
     *
     * @param activityId the value for workitem_detail.activity_id
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.activity_name
     *
     * @return the value of workitem_detail.activity_name
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.activity_name
     *
     * @param activityName the value for workitem_detail.activity_name
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.operator
     *
     * @return the value of workitem_detail.operator
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.operator
     *
     * @param operator the value for workitem_detail.operator
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.operate_time
     *
     * @return the value of workitem_detail.operate_time
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.operate_time
     *
     * @param operateTime the value for workitem_detail.operate_time
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.approval_comment
     *
     * @return the value of workitem_detail.approval_comment
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getApprovalComment() {
        return approvalComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.approval_comment
     *
     * @param approvalComment the value for workitem_detail.approval_comment
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setApprovalComment(String approvalComment) {
        this.approvalComment = approvalComment == null ? null : approvalComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.remark
     *
     * @return the value of workitem_detail.remark
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.remark
     *
     * @param remark the value for workitem_detail.remark
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.status
     *
     * @return the value of workitem_detail.status
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.status
     *
     * @param status the value for workitem_detail.status
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.ext1
     *
     * @return the value of workitem_detail.ext1
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.ext1
     *
     * @param ext1 the value for workitem_detail.ext1
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.ext2
     *
     * @return the value of workitem_detail.ext2
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.ext2
     *
     * @param ext2 the value for workitem_detail.ext2
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workitem_detail.ext3
     *
     * @return the value of workitem_detail.ext3
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workitem_detail.ext3
     *
     * @param ext3 the value for workitem_detail.ext3
     *
     * @mbggenerated Sun Sep 30 15:25:00 CST 2018
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }
}