package com.tj720.model.common.area;

import java.util.Date;

public class MipArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.pid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.shortname
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.merger_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String mergerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.pinyin
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.code
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.zip_code
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.first
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String first;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.lng
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.lat
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_area.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.id
     *
     * @return the value of mip_area.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.id
     *
     * @param id the value for mip_area.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.pid
     *
     * @return the value of mip_area.pid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.pid
     *
     * @param pid the value for mip_area.pid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.shortname
     *
     * @return the value of mip_area.shortname
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.shortname
     *
     * @param shortname the value for mip_area.shortname
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.name
     *
     * @return the value of mip_area.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.name
     *
     * @param name the value for mip_area.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.merger_name
     *
     * @return the value of mip_area.merger_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.merger_name
     *
     * @param mergerName the value for mip_area.merger_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName == null ? null : mergerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.level
     *
     * @return the value of mip_area.level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.level
     *
     * @param level the value for mip_area.level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.pinyin
     *
     * @return the value of mip_area.pinyin
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.pinyin
     *
     * @param pinyin the value for mip_area.pinyin
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.code
     *
     * @return the value of mip_area.code
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.code
     *
     * @param code the value for mip_area.code
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.zip_code
     *
     * @return the value of mip_area.zip_code
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.zip_code
     *
     * @param zipCode the value for mip_area.zip_code
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.first
     *
     * @return the value of mip_area.first
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getFirst() {
        return first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.first
     *
     * @param first the value for mip_area.first
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setFirst(String first) {
        this.first = first == null ? null : first.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.lng
     *
     * @return the value of mip_area.lng
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.lng
     *
     * @param lng the value for mip_area.lng
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.lat
     *
     * @return the value of mip_area.lat
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.lat
     *
     * @param lat the value for mip_area.lat
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.status
     *
     * @return the value of mip_area.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.status
     *
     * @param status the value for mip_area.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.sequence
     *
     * @return the value of mip_area.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.sequence
     *
     * @param sequence the value for mip_area.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_area.createTime
     *
     * @return the value of mip_area.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_area.createTime
     *
     * @param createtime the value for mip_area.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}