package com.tj720.model.common.system.user;

import java.util.Date;

public class MipUser implements java.io.Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.org_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.password
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.phone
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.qq_openid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String qqOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.weixin_unionid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String weixinUnionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.email
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.sex
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.nick_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.avatarUrl
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String avatarurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.area_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.birthday
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.province
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.city
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.county
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.job
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.tags
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.create_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.login_times
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer loginTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.last_login_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.login_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.isdelete
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user.description
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.id
     *
     * @return the value of mip_user.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    
    
    private String creatStaTime;
    private String creatOverTime;
    private String lastLongStaTime;
    private String lastLongOverTime;
    
    private String birth;
    
    private String tag;
    
    private String orgName;
    
    
    public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getCreatStaTime() {
		return creatStaTime;
	}

	public void setCreatStaTime(String creatStaTime) {
		this.creatStaTime = creatStaTime;
	}

	public String getCreatOverTime() {
		return creatOverTime;
	}

	public void setCreatOverTime(String creatOverTime) {
		this.creatOverTime = creatOverTime;
	}

	public String getLastLongStaTime() {
		return lastLongStaTime;
	}

	public void setLastLongStaTime(String lastLongStaTime) {
		this.lastLongStaTime = lastLongStaTime;
	}

	public String getLastLongOverTime() {
		return lastLongOverTime;
	}

	public void setLastLongOverTime(String lastLongOverTime) {
		this.lastLongOverTime = lastLongOverTime;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.id
     *
     * @param id the value for mip_user.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.org_id
     *
     * @return the value of mip_user.org_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.org_id
     *
     * @param orgId the value for mip_user.org_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.password
     *
     * @return the value of mip_user.password
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.password
     *
     * @param password the value for mip_user.password
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.phone
     *
     * @return the value of mip_user.phone
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.phone
     *
     * @param phone the value for mip_user.phone
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.qq_openid
     *
     * @return the value of mip_user.qq_openid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getQqOpenid() {
        return qqOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.qq_openid
     *
     * @param qqOpenid the value for mip_user.qq_openid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setQqOpenid(String qqOpenid) {
        this.qqOpenid = qqOpenid == null ? null : qqOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.weixin_unionid
     *
     * @return the value of mip_user.weixin_unionid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getWeixinUnionid() {
        return weixinUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.weixin_unionid
     *
     * @param weixinUnionid the value for mip_user.weixin_unionid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setWeixinUnionid(String weixinUnionid) {
        this.weixinUnionid = weixinUnionid == null ? null : weixinUnionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.email
     *
     * @return the value of mip_user.email
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.email
     *
     * @param email the value for mip_user.email
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.sex
     *
     * @return the value of mip_user.sex
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.sex
     *
     * @param sex the value for mip_user.sex
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.nick_name
     *
     * @return the value of mip_user.nick_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.nick_name
     *
     * @param nickName the value for mip_user.nick_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.name
     *
     * @return the value of mip_user.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.name
     *
     * @param name the value for mip_user.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.avatarUrl
     *
     * @return the value of mip_user.avatarUrl
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getAvatarurl() {
        return avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.avatarUrl
     *
     * @param avatarurl the value for mip_user.avatarUrl
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl == null ? null : avatarurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.area_id
     *
     * @return the value of mip_user.area_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.area_id
     *
     * @param areaId the value for mip_user.area_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.birthday
     *
     * @return the value of mip_user.birthday
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.birthday
     *
     * @param birthday the value for mip_user.birthday
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.province
     *
     * @return the value of mip_user.province
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.province
     *
     * @param province the value for mip_user.province
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.city
     *
     * @return the value of mip_user.city
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.city
     *
     * @param city the value for mip_user.city
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.county
     *
     * @return the value of mip_user.county
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.county
     *
     * @param county the value for mip_user.county
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCounty(Integer county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.job
     *
     * @return the value of mip_user.job
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.job
     *
     * @param job the value for mip_user.job
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.tags
     *
     * @return the value of mip_user.tags
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.tags
     *
     * @param tags the value for mip_user.tags
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setTags(Integer tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.create_time
     *
     * @return the value of mip_user.create_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.create_time
     *
     * @param createTime the value for mip_user.create_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.login_times
     *
     * @return the value of mip_user.login_times
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getLoginTimes() {
        return loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.login_times
     *
     * @param loginTimes the value for mip_user.login_times
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.last_login_time
     *
     * @return the value of mip_user.last_login_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.last_login_time
     *
     * @param lastLoginTime the value for mip_user.last_login_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLastLoginTime(Integer lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.createTime
     *
     * @return the value of mip_user.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.createTime
     *
     * @param createtime the value for mip_user.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.status
     *
     * @return the value of mip_user.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.status
     *
     * @param status the value for mip_user.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.sequence
     *
     * @return the value of mip_user.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.sequence
     *
     * @param sequence the value for mip_user.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.login_type
     *
     * @return the value of mip_user.login_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.login_type
     *
     * @param loginType the value for mip_user.login_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLoginType(Integer loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.isdelete
     *
     * @return the value of mip_user.isdelete
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.isdelete
     *
     * @param isdelete the value for mip_user.isdelete
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user.description
     *
     * @return the value of mip_user.description
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user.description
     *
     * @param description the value for mip_user.description
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	public String getBirth() {
		return birth;
	}

	public void setBirth(String birth) {
		this.birth = birth;
	}

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}
    
	
    
}