package com.tj720.model.common.system.user;

import java.util.Date;

public class MipUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user_role.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user_role.user_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user_role.role_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user_role.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user_role.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_user_role.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user_role.id
     *
     * @return the value of mip_user_role.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user_role.id
     *
     * @param id the value for mip_user_role.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user_role.user_id
     *
     * @return the value of mip_user_role.user_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user_role.user_id
     *
     * @param userId the value for mip_user_role.user_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user_role.role_id
     *
     * @return the value of mip_user_role.role_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user_role.role_id
     *
     * @param roleId the value for mip_user_role.role_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user_role.status
     *
     * @return the value of mip_user_role.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user_role.status
     *
     * @param status the value for mip_user_role.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user_role.sequence
     *
     * @return the value of mip_user_role.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user_role.sequence
     *
     * @param sequence the value for mip_user_role.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_user_role.createTime
     *
     * @return the value of mip_user_role.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_user_role.createTime
     *
     * @param createtime the value for mip_user_role.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}